### ISSUE TITLE
请更新一下CALIBRE的版本

### ISSUE THREAD

**Issue by lottelucky** [Finios/calibre-server#1]
其他都好，就是CALIBRE的版本太旧了，特别是读书模块，最好能更新一下，谢谢。

**Comment by Finios** [comment]
In wich case is the reading module outdated? The image is build with the latest version or with the version you chose in build argument calibre_version.

**Comment by Finios** [comment]
Newest versions of the container are build automaticly on a Synology DS1513+ and are pushed to [dockerhub](https://hub.docker.com/r/finios/calibre-server). I'm testing the container on the same machine I'm building it, so I can only see if it work on my side.
