### ISSUE TITLE
Multiple libraries not working

### ISSUE THREAD

**Issue by scbarrett** [Finios/calibre-server#3]
I think this image is just what I need. Its support for multiple libraries is key.

Single library works fine. When I try two libs Docker gets confused, thinking the second lib is the repository. This command yields the following error:

`docker run -d -p 8082:8080 -v /home/spokes/data-aux/collections/books/LL_Doc-Base/LL_Core-Libs:/calibre-lib -e LIBRARY=/calibre-lib/LL_Case /calibre-lib/LL_Reference --name calibre finios/calibre-server:v5.43.0`

docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.

**Comment by Finios** [comment]
Hi scbarrett,
you have to add your LIBRARY environment variable in ' ' or " ".

`docker run -d -p 8082:8080 -v /home/spokes/data-aux/collections/books/LL_Doc-Base/LL_Core-Libs:/calibre-lib -e LIBRARY='/calibre-lib/LL_Case /calibre-lib/LL_Reference' --name calibre finios/calibre-server:v5.43.0`

or 

`docker run -d -p 8082:8080 -v /home/spokes/data-aux/collections/books/LL_Doc-Base/LL_Core-Libs:/calibre-lib -e LIBRARY="/calibre-lib/LL_Case /calibre-lib/LL_Reference" --name calibre finios/calibre-server:v5.43.0`

I have correct the mistake in the [README.md](https://github.com/Finios/calibre-server/blob/master/README.md).

**Comment by scbarrett** [comment]
One combination I didn't try! I'll let you know. Thanks!

**Comment by scbarrett** [comment]
Works with double quotes. Get the same error with single quotes. This is great! Now, on to better things...
