### ISSUE TITLE
Trouble with -e OTHERPARAM

### ISSUE THREAD

**Issue by scbarrett** [Finios/calibre-server#4]
Almost there! Trying to add these options to the docker run:

-e OTHERPARAM --book-list-mode custom_list -e OTHERPARAM --custom-list-template LL_Web-List.json

generate usage errors. I can quiet them by adding equal signs and quotes, e.g., ...PARAM="--book..." That gets past the syntax checker, but the container does not start.

**Comment by scbarrett** [comment]
Thinking this has something to do with the path. Tried -e OTHERPARAM="--enable-local-write" and that worked, or at least the image started.

**Comment by scbarrett** [comment]
Got it! Had to put the .json in a known location, and provide the path:
-e OTHERPARAM="--custom-list-template /calibre-lib/LL_Web-List.json"

Sorry to be using your issues for my debugging. BTW, this image is near perfect. Thanks for your labor.

**Comment by Finios** [comment]
No problem. Open as many issues as you need to solve your problems. I will try to help.
